[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

# Ensure Netlify knows this is a single page application
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200